version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    commit-message:
      prefix: cargo

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    commit-message:
      prefix: npm
